version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: notegeek-mongo
    ports:
      - "27017:27017" # Exposes MongoDB port to the host machine
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./data/db:/data/db # Persists database data on the host
      - ./data/backups:/data/backups # For potential backup service later
    networks:
      - notegeek_network
    restart: always

networks:
  notegeek_network:
    driver: bridge